-- About page settings — run this once in the Supabase SQL editor.

-- Single-row table holding the Mission / Vision section images
create table if not exists about_settings (
  id bigint primary key generated by default as identity,
  mission_image_url text,
  vision_image_url text
);

-- Team members shown on the About page (the app allows up to 3)
create table if not exists team_members (
  id bigint primary key generated by default as identity,
  name text not null,
  description text,
  image_url text,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);

alter table about_settings enable row level security;
alter table team_members enable row level security;

-- Public (anon) read access — writes go through the service role only
create policy "Public read about_settings"
  on about_settings for select using (true);

create policy "Public read team_members"
  on team_members for select using (true);
