-- Blog posts — run this once in the Supabase SQL editor.

create table if not exists blog_posts (
  id bigint primary key generated by default as identity,
  title text not null,
  slug text not null unique,
  excerpt text not null default '',
  content_html text not null default '',
  cover_image_url text not null default '',
  is_active boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table blog_posts enable row level security;

-- Public (anon) read access — writes go through the service role only.
-- Matches every other content table: RLS stays open, and callers filter
-- on is_active themselves (public pages filter it, the admin list doesn't).
drop policy if exists "Public read blog_posts" on blog_posts;
create policy "Public read blog_posts"
  on blog_posts for select using (true);
