-- Product categories — run this once in the Supabase SQL editor.

create table if not exists categories (
  id bigint primary key generated by default as identity,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table categories enable row level security;

-- Public (anon) read access — writes go through the service role only
create policy "Public read categories"
  on categories for select using (true);

-- Seed the categories already in use by existing products so nothing breaks
insert into categories (name)
values
  ('Signature Hamper Collection'),
  ('Artisan Gift Curation'),
  ('Premium Baby Essential'),
  ('Corporate Gift'),
  ('Custom Order')
on conflict (name) do nothing;
