-- Testimonials / client results — run this once in the Supabase SQL editor.

create table if not exists testimonials (
  id bigint primary key generated by default as identity,
  client_name text not null,
  company text,
  result_image_url text,
  quote text not null,
  result_text text,
  is_active boolean not null default true,
  sort_order int not null default 1,
  created_at timestamptz not null default now()
);

-- If the table already exists from a previous run, migrate it:
-- swap the client "photo" for a "result image" instead.
alter table testimonials add column if not exists result_image_url text;
alter table testimonials drop column if exists photo_url;

alter table testimonials enable row level security;

-- Public (anon) read access — writes go through the service role only
drop policy if exists "Public read testimonials" on testimonials;
create policy "Public read testimonials"
  on testimonials for select using (true);

-- Example testimonials with no result image — only seeded if the table is empty,
-- so this file is safe to re-run without duplicating rows.
insert into testimonials (client_name, company, quote, result_text, sort_order)
select * from (values
  (
    'Sarah Amelia',
    'Tokopedia',
    'Custom at Suka made our corporate gifting effortless — every hamper felt personal and the whole team was impressed by the quality.',
    'Delivered 500 hampers in 2 weeks',
    1
  ),
  (
    'Rangga Pratama',
    'Gojek',
    'From the first call to delivery, communication was clear and the final product exceeded what we pictured. Highly recommend for any custom order.',
    'Repeat client — 3 orders in 6 months',
    2
  )
) as seed(client_name, company, quote, result_text, sort_order)
where not exists (select 1 from testimonials);
