-- WhatsApp popup settings — run this once in the Supabase SQL editor.

-- Single-row table holding the floating WhatsApp popup's editable text
create table if not exists whatsapp_settings (
  id bigint primary key generated by default as identity,
  greeting_message text not null,
  prefilled_message text not null
);

alter table whatsapp_settings enable row level security;

-- Public (anon) read access — writes go through the service role only
drop policy if exists "Public read whatsapp_settings" on whatsapp_settings;
create policy "Public read whatsapp_settings"
  on whatsapp_settings for select using (true);

-- Seed the default row (matches the previous hardcoded text) if none exists yet
insert into whatsapp_settings (greeting_message, prefilled_message)
select
  'Hi there! 👋 How can we help you today? Let us know what you need and we''ll craft something special just for you.',
  'Hi! I''d like to know more about your products.'
where not exists (select 1 from whatsapp_settings);
